### ISSUE TITLE
pyxid.get_xid_devices() throws errors on every windows machine I try

### ISSUE THREAD

**Issue by nicolahadwen** [cedrus-opensource/pyxid#10]
Everything works perfectly on my mac, but on windows when I try to call pyxid.get_xid_devices(). An error is thrown from the open method in serialwin32 in the pyserial package. It basically says that self.name is an integer object, when it its supposed to be a string object with "COM", then a digit.

**Comment by terronymous-boosh** [comment]
I appear to have the same problem - Windows 7, PsychoPy 1.84.1 gives this error. Don't suppose you know how to fix it?

**Comment by peircej** [comment]
Actually this is a matter of having the right version of pyserial to match with the current version of pyxid. The latest version of pyserial and the latest version of pyxid together are fine. PsychoPy 1.85 will provide these in the Standalone

**Comment by texton** [comment]
I bought rb_540, and got the same error message as nicolahadwen got.
I tracked down to serial_wrapper.py, and modified like following, and it works now.
In order to modify the file, you have to run the program PsychoPy with administrative privilege (click Psychopy icon, not shortcut icon, with right mouse button, and select "run with administrative privilege"). Wording might be wrong because I am using the Windows Korean version. 

from line 62---------------------
    @staticmethod
    def available_ports():
        """
        Scans COM1 through COM255 for available serial ports

        returns a list of available ports
        """
        ports = []

        for i in range(256):
            try:
                aPort = 'COM'+str(i) #Here is what I add.
                p = Serial(aPort)       #and modified
                p.close()
                ports.append(p)
            except SerialException:
                pass

        return ports

**Comment by peircej** [comment]
I think this was already fixed here by: ced22e331f
I'll check that is included in the PsychoPy standalone in the next release
