### ISSUE TITLE
Clear history of response

### ISSUE THREAD

**Issue by ferponcem** [cedrus-opensource/pyxid#20]
Hello!

I am using pyxid2 with a Cedrus RB-730 and Opensesame interface and I am trying to use it to collect responses from the different buttons with this code: 

    import pyxid2
    import time
  
    devices = pyxid2.get_xid_devices()
    dev = devices[0] # get the first device to use
    print(dev)
    dev.reset_base_timer()
    dev.reset_rt_timer()
  
    if dev.is_response_device():
        print ("Press a key!")
        while not dev.has_response():
            dev.poll_for_response()
  
        response = dev.get_next_response()
        print(response)
        dev.clear_response_queue()

However, the dev.clear_response_queue() doesn't seem to be called because the 'pressed' key of the response remains True, so it doesn't collect the next response.

Do you have any ideas or sugggestions?? Thanks so much

**Comment by habboud** [comment]
If you run the code and press a button, **two** responses will be put in the queue: a press and a release. The code then polls for a single response and it comes up with a single ‘pressed’ response that you then print and correctly identify as a pressed response. Then you clear the response queue, which clears out the second “release” response from the queue and has no visible effect on the code here.

Is this not what you expect to happen?

**Comment by ferponcem** [comment]
Yeah, but then when I try to get the next response, it doesn't collect it because the status of the response remains as pressed = True, so it doesn't poll for it and then we have to miss one trial for it to get set as False and then run.  I have tried to manually set the pressed key as False but it does not work, and I have also tried to clear the response in different parts of the code but it's not working either.

**Comment by ematsakCedrus** [comment]
The response you collected stays the same, because you collected it and you have it. That part has nothing to do with the response queue.

As for the rest, here's what's going on. When you press the physical key on the device, two sets of bytes describing this go into the serial buffer -- one for the press and one for the release. When you call poll_for_response(), pyxid checks the serial buffer for bytes constituting a response packet, and puts a response object in its internal response queue. It does so once per poll_for_response() call.

In the provided sample you only call poll_for_response() once, so the release never gets processed by pyxid, so it's still in the buffer and is not in the response queue. Furthermore, if it was in the response queue, you would have destroyed it with the clear_response_queue() call. In this snippet the call does nothing, since you retrieved the key press from the queue with get_next_response(), and the key release is still in the serial buffer.

If you want to collect more responses, you need to poll for them by calling poll_for_response(), and then retrieve them by calling get_next_response().

**Comment by ferponcem** [comment]
Thank you so much! So, how can I get the release processed from the serial buffer?? Thanks a lot again!

**Comment by ematsakCedrus** [comment]
The same way you got the press. Calling poll_for_response() to and then get_next_response().

**Comment by ematsakCedrus** [comment]
You can do something like this to poll for responses in press-release pairs and then print them at once.

```
import pyxid2
import time

devices = pyxid2.get_xid_devices()
dev = devices[0]

print ("Press a key!")
while dev.response_queue_size() < 2:
    dev.poll_for_response()

while dev.has_response():
    response = dev.get_next_response()
    print(response)
```

**Comment by ferponcem** [comment]
It worked perfectly!
Thank you so so much (:
